spring.application.name=scheduler
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.active=local
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Security Settings
app.security.cors.allowed-origins=http://localhost:5173
app.security.cookie.secure=false
app.security.cookie.same-site=Lax
app.security.cookie.domain=

# Session Limits
app.security.session.max-active-sessions=5

